import type { CollectionKind } from "@icons-db/core";

/** Curated v1 icon sets (Iconify prefixes). All permissive licences. */
export const PREFIXES = [
  "lucide",
  "heroicons",
  "tabler",
  "ph",
  "ri",
  "material-symbols",
  "bi",
  "ion",
  "iconoir",
  "carbon",
  "fluent",
  "radix-icons",
  "octicon",
  "simple-icons",
  "akar-icons",
  "gg",
  "teenyicons",
  "mdi",
  "solar",
  "majesticons",
  // emoji
  "twemoji",
  "noto",
  "fluent-emoji-flat",
  "fluent-emoji-high-contrast",
  "openmoji",
  "fluent-emoji",
  "emojione",
  "streamline-emojis",
  // icons (batch 2)
  "fa6-solid",
  "fa6-regular",
  "mingcute",
  "hugeicons",
  "line-md",
  "uil",
  "uim",
  "uis",
  "eva",
  "feather",
  "bx",
  "bxs",
  "mage",
  "pixelarticons",
  "f7",
  "jam",
  "la",
  "humbleicons",
  "weui",
  // brands & logos
  "fa6-brands",
  "bxl",
  "logos",
  "devicon",
  "skill-icons",
  "vscode-icons",
  "catppuccin",
  "flag",
  "circle-flags",
  "flagpack",
] as const;

export const KINDS: Record<string, CollectionKind> = {
  "simple-icons": "brands",
  twemoji: "emoji",
  noto: "emoji",
  "fluent-emoji-flat": "emoji",
  "fluent-emoji-high-contrast": "emoji",
  openmoji: "emoji",
  "fluent-emoji": "emoji",
  emojione: "emoji",
  "streamline-emojis": "emoji",
  "fa6-brands": "brands",
  bxl: "brands",
  logos: "brands",
  devicon: "brands",
  "skill-icons": "brands",
  "vscode-icons": "brands",
  catppuccin: "brands",
  flag: "brands",
  "circle-flags": "brands",
  flagpack: "brands",
};

export const HOMEPAGES: Record<string, string> = {
  lucide: "https://lucide.dev",
  heroicons: "https://heroicons.com",
  tabler: "https://tabler.io/icons",
  ph: "https://phosphoricons.com",
  ri: "https://remixicon.com",
  "material-symbols": "https://fonts.google.com/icons",
  bi: "https://icons.getbootstrap.com",
  ion: "https://ionic.io/ionicons",
  iconoir: "https://iconoir.com",
  carbon: "https://carbondesignsystem.com/elements/icons/library/",
  fluent: "https://github.com/microsoft/fluentui-system-icons",
  "radix-icons": "https://www.radix-ui.com/icons",
  octicon: "https://primer.style/octicons",
  "simple-icons": "https://simpleicons.org",
  "akar-icons": "https://akaricons.com",
  gg: "https://css.gg",
  teenyicons: "https://teenyicons.com",
  mdi: "https://pictogrammers.com/library/mdi/",
  solar: "https://www.figma.com/community/file/1166831539721848736",
  majesticons: "https://www.majesticons.com",
  twemoji: "https://github.com/jdecked/twemoji",
  noto: "https://github.com/googlefonts/noto-emoji",
  "fluent-emoji-flat": "https://github.com/microsoft/fluentui-emoji",
  "fluent-emoji-high-contrast": "https://github.com/microsoft/fluentui-emoji",
  openmoji: "https://openmoji.org",
  "fluent-emoji": "https://github.com/microsoft/fluentui-emoji",
  emojione: "https://github.com/joypixels/emojione",
  "streamline-emojis": "https://www.streamlinehq.com/emojis",
  "fa6-solid": "https://fontawesome.com",
  "fa6-regular": "https://fontawesome.com",
  "fa6-brands": "https://fontawesome.com",
  mingcute: "https://www.mingcute.com",
  hugeicons: "https://hugeicons.com",
  "line-md": "https://cyberalien.github.io/line-md/",
  uil: "https://iconscout.com/unicons",
  uim: "https://iconscout.com/unicons",
  uis: "https://iconscout.com/unicons",
  eva: "https://akveo.github.io/eva-icons/",
  feather: "https://feathericons.com",
  bx: "https://boxicons.com",
  bxs: "https://boxicons.com",
  bxl: "https://boxicons.com",
  mage: "https://mageicons.com",
  pixelarticons: "https://pixelarticons.com",
  f7: "https://framework7.io/icons/",
  jam: "https://jam-icons.com",
  la: "https://icons8.com/line-awesome",
  humbleicons: "https://humbleicons.com",
  weui: "https://github.com/weui/weui-icon",
  logos: "https://svgporn.com",
  devicon: "https://devicon.dev",
  "skill-icons": "https://skillicons.dev",
  "vscode-icons": "https://github.com/vscode-icons/vscode-icons",
  catppuccin: "https://github.com/catppuccin/vscode-icons",
  flag: "https://flagicons.lipis.dev",
  "circle-flags": "https://hatscripts.github.io/circle-flags/",
  flagpack: "https://flagpack.xyz",
};
