/** Curated v1 icon sets (Iconify prefixes). All permissive licences. */
export const PREFIXES = [
  "lucide",
  "heroicons",
  "tabler",
  "ph",
  "ri",
  "material-symbols",
  "bi",
  "ion",
  "iconoir",
  "carbon",
  "fluent",
  "radix-icons",
  "octicon",
  "simple-icons",
  "akar-icons",
  "gg",
  "teenyicons",
  "mdi",
  "solar",
  "majesticons",
] as const;

export const HOMEPAGES: Record<string, string> = {
  lucide: "https://lucide.dev",
  heroicons: "https://heroicons.com",
  tabler: "https://tabler.io/icons",
  ph: "https://phosphoricons.com",
  ri: "https://remixicon.com",
  "material-symbols": "https://fonts.google.com/icons",
  bi: "https://icons.getbootstrap.com",
  ion: "https://ionic.io/ionicons",
  iconoir: "https://iconoir.com",
  carbon: "https://carbondesignsystem.com/elements/icons/library/",
  fluent: "https://github.com/microsoft/fluentui-system-icons",
  "radix-icons": "https://www.radix-ui.com/icons",
  octicon: "https://primer.style/octicons",
  "simple-icons": "https://simpleicons.org",
  "akar-icons": "https://akaricons.com",
  gg: "https://css.gg",
  teenyicons: "https://teenyicons.com",
  mdi: "https://pictogrammers.com/library/mdi/",
  solar: "https://www.figma.com/community/file/1166831539721848736",
  majesticons: "https://www.majesticons.com",
};
